### PR TITLE
Avoid an infinity loop in LineObserver()

### PR DESCRIPTION
**Pull request by geext-dk**
Currently if somehow terminator bytes haven't been found in the buffer, the function just continues the outer loop, but it can't acquire more because the buffer isn't empty. So we must first try to acquire bytes and if we get nothing then we will just replace the buffer with an empty byte array. Or else we will have a chance to find terminator bytes this time.

P. S. This project really lacks tests.
Also, why there is no .sln file in the repo? It is really hard to add a tests project to the repo without a .sln file.
And is there a particular reason for a such code style (tabs instead of spaces, this.something to access member variables, Int32 instead of int, etc)?

### CODE REVIEW

**Comment by geext-dk** [comment]
Sorry I accidently commited different changes to the branch so I'll create another pull request

**Comment by alexforster** [comment]
> Currently if somehow terminator bytes haven't been found in the buffer, the function just continues the outer loop, but it can't acquire more because the buffer isn't empty. So we must first try to acquire bytes and if we get nothing then we will just replace the buffer with an empty byte array. Or else we will have a chance to find terminator bytes this time.

That's true. As implemented, the worker does expect that a (the first?) read from the socket will contain at least one line within the first 4096 bytes. This works by depending on an implementation detail of the Asterisk AMI implementation, but if a theoretical Asterisk-like server uses `TCP_NODELAY` or emits one reeeeeally long line, then that assumption might not hold true. Is this the case you're dealing with?

> P. S. This project really lacks tests.

Yeah. It's _testable_ by mocking an Asterisk server using a `MemoryStream` object.

> why there is no .sln file in the repo?

I just haven't committed one because I develop it as part of a larger project. I've assumed others would either use the Nuget package or reference this repository as a git submodule in their own solutions.

> is there a particular reason for a such code style

¯\\\_(ツ)\_/¯ 

> tabs instead of spaces

I think tabs for indentation and spaces for alignment is the One True Way.
https://dev.to/alexandersandberg/why-we-should-default-to-tabs-instead-of-spaces-for-an-accessible-first-environment-101f

> this.something

I don't like `m_something` or `_something`

> Int32 instead of int

My affinity for being explicit about integer sizes comes from C, where it's better to use `int32_t` instead of `int`, since `int` could technically be 16 bits.

**Comment by alexforster** [comment]
Can you try the branch `support-socket-timeout`

**Comment by wluke** [comment]
This branch fixes the issue (I was also experiencing it until I updated to use this branch)

**Comment by alexforster** [comment]
This branch but _not_ the `support-socket-timeout` branch?

**Pull request closed without merging**
